name: Check  # Название workflow

on: push  # Запускать при коммите в репозиторий

jobs:  # Определение различных задач (jobs)
  lint:  # Первая задача - линтинг кода
    runs-on: ubuntu-latest  # Задача будет выполняться на последней версии Ubuntu
    steps:  # Шаги, которые нужно выполнить в этой задаче
      - name: Checkout  # Шаг для проверки кода из репозитория
        uses: actions/checkout@v3  # Использует действие для проверки репозитория
      - name: Install deps  # Шаг установки зависимостей
        run: npm i  # Выполняет команду npm install для установки зависимостей
      - name: Lint  # Шаг для линтинга
        run: npm run build  # Выполняет команду npm run build (это может включать линтинг, если это прописано в скрипте)

  test:  # Вторая задача - тестирование
    needs: [lint]  # Эта задача будет выполняться только после успешного завершения задачи линтинга
    strategy:  # Стратегия тестирования
      matrix:  # Повторение тестирования для разных версий Node.js
        version: [14, 16, 18]  # Версии Node.js, которые будут тестироваться
    runs-on: ubuntu-latest  # Задача будет выполняться на последней версии Ubuntu
    steps:  # Шаги для выполнения
      - name: Checkout  # Шаг для проверки кода из репозитория
        uses: actions/checkout@v3  # Использует действие для проверки репозитория
      - name: Install deps  # Шаг установки зависимостей
        run: npm i  # Выполняет команду npm install для установки зависимостей
      - name: Lint  # Шаг для линтинга (возможно, вы имели в виду запуск тестов вместо линтинга)
        run: npm run build  # Выполняет команду npm run build (обычно это для сборки, а не для тестирования)